deployment:
  tasks:
    – export DEPLOYPATH=/home/reavowmy/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp earth.png $DEPLOYPATH
    - /bin/cp cv.pdf $DEPLOYPATH
